name: Deploy to Yandex Cloud Storage

on:
  push:
    branches:
      - main # Запускать при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Укажи свою версию Node.js

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Yandex Cloud S3 Upload
        uses: a-mans-exp/sync-s3-bucket@v1
        with:
          aws_access_key_id: ${{ secrets.YC_KEY_ID }}
          aws_secret_access_key: ${{ secrets.YC_SECRET_KEY }}
          aws_bucket_name: ${{ secrets.YC_BUCKET_NAME }}
          local_path: "./dist"
          endpoint_url: "https://storage.yandexcloud.net" # Эндпоинт S3 Яндекса